-- create DB

CREATE TABLE TP_OBJECT_TYPES (
  OBJECT_TYPE_ID NUMBER(20) NOT NULL,
  PARENT_ID NUMBER(20) NULL,
  NAME VARCHAR2(250) NOT NULL,
  DESCRIPTION VARCHAR2(4000),

  PRIMARY KEY (OBJECT_TYPE_ID),

  CONSTRAINT FK_TP_OBJ_TYPES_OBJ_TYPES
    FOREIGN KEY (PARENT_ID)
    REFERENCES TP_OBJECT_TYPES (OBJECT_TYPE_ID) ON DELETE CASCADE
);

CREATE INDEX OBJ_TYPES_PARENT_TP_IDX ON TP_OBJECT_TYPES (PARENT_ID);


CREATE TABLE TP_OBJECTS (
  OBJECT_ID NUMBER(20) NOT NULL,
  OBJECT_TYPE_ID NUMBER(20) NOT NULL,
  PARENT_ID NUMBER(20) NULL,
  NAME VARCHAR2(250) NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  ORDER_NUM NUMBER(10),

  PRIMARY KEY (OBJECT_ID),

  CONSTRAINT FK_TP_OBJECTS_OBJECT_TYPES
    FOREIGN KEY (OBJECT_TYPE_ID)
    REFERENCES TP_OBJECT_TYPES (OBJECT_TYPE_ID),
  CONSTRAINT FK_TP_OBJECTS_OBJECTS
    FOREIGN KEY (PARENT_ID)
    REFERENCES TP_OBJECTS (OBJECT_ID) ON DELETE CASCADE
);

CREATE INDEX OBJECTS_OBJECT_TYPE_TP_IDX ON TP_OBJECTS (OBJECT_TYPE_ID);
CREATE INDEX OBJECTS_PARENT_TP_IDX ON TP_OBJECTS (PARENT_ID);


CREATE TABLE TP_LIST_VALUES (
  LIST_VALUE_ID NUMBER(20) NOT NULL,
  LIST_VALUE_TYPE_ID NUMBER(20) NOT NULL,
  VALUE VARCHAR2(250),
  ORDER_NUM NUMBER(10),

  PRIMARY KEY (LIST_VALUE_ID)
);

CREATE INDEX LIST_VALUES_LV_TYPE_TP_IDX ON TP_LIST_VALUES (LIST_VALUE_TYPE_ID);


CREATE TABLE TP_ATTRIBUTE_TYPES (
  ATTR_TYPE_ID NUMBER(20) NOT NULL,
  LIST_VALUE_TYPE_ID NUMBER(20) NULL,
  NAME VARCHAR2(250) NOT NULL,
  DATA_TYPE NUMBER(10) NOT NULL,

  PRIMARY KEY (ATTR_TYPE_ID)
--   CONSTRAINT FK_TP_ATTRIBUTE_TYPES_LIST_VALUES
--     FOREIGN KEY (LIST_VALUE_TYPE_ID)
--     REFERENCES TP_LIST_VALUES (LIST_VALUE_TYPE_ID)
);

CREATE INDEX ATTR_TYPES_LV_TYPE_TP_IDX ON TP_ATTRIBUTE_TYPES (LIST_VALUE_TYPE_ID);


CREATE TABLE TP_ATTRIBUTES (
  ATTR_ID NUMBER(20) NOT NULL,
  ATTR_TYPE_ID NUMBER(20) NOT NULL,
  NAME VARCHAR2(250) NOT NULL,
  ORDER_NUM NUMBER(10),
  PROPERTIES VARCHAR2(4000),
  MASK VARCHAR2(200),

  PRIMARY KEY (ATTR_ID),

  CONSTRAINT FK_TP_ATTR_ATTR_TYPES
    FOREIGN KEY (ATTR_TYPE_ID)
    REFERENCES TP_ATTRIBUTE_TYPES (ATTR_TYPE_ID)
);

CREATE INDEX ATTR_ATTR_TYPE_TP_IDX ON TP_ATTRIBUTES (ATTR_TYPE_ID);


CREATE TABLE TP_ATTR_OBJ_TYPES (
  OBJECT_TYPE_ID NUMBER(20) NOT NULL,
  ATTR_ID NUMBER(20) NOT NULL,

  CONSTRAINT FK_TP_ATTR_OBJ_T_OBJ_T
    FOREIGN KEY (OBJECT_TYPE_ID)
    REFERENCES TP_OBJECT_TYPES (OBJECT_TYPE_ID),
  CONSTRAINT FK_TP_ATTR_OBJ_T_ATTRIBUTES
    FOREIGN KEY (ATTR_ID)
    REFERENCES TP_ATTRIBUTES (ATTR_ID)
);

CREATE INDEX ATTR_OBJ_T_OBJ_T_TP_IDX ON TP_ATTR_OBJ_TYPES (OBJECT_TYPE_ID);
CREATE INDEX ATTR_OBJ_T_ATTR_TP_IDX ON TP_ATTR_OBJ_TYPES (ATTR_ID);


CREATE TABLE TP_PARAMS (
  OBJECT_ID NUMBER(20) NOT NULL,
  ATTR_ID NUMBER(20) NOT NULL,
  REFERENCE NUMBER(20),
  LIST_VALUE_ID NUMBER(20),
  DATE_VALUE TIMESTAMP,
  VALUE VARCHAR2(45),
  ORDER_NUM NUMBER(10),

  CONSTRAINT FK_TP_PARAMS_OBJECTS
    FOREIGN KEY (OBJECT_ID)
    REFERENCES TP_OBJECTS (OBJECT_ID) ON DELETE CASCADE ,
  CONSTRAINT FK_TP_PARAMS_ATTRIBUTES
    FOREIGN KEY (ATTR_ID)
    REFERENCES TP_ATTRIBUTES (ATTR_ID) ON DELETE CASCADE ,
  CONSTRAINT FK_TP_PARAMS_LIST_VALUES
    FOREIGN KEY (LIST_VALUE_ID)
    REFERENCES TP_LIST_VALUES (LIST_VALUE_ID) ON DELETE CASCADE ,
  CONSTRAINT FK_TP_REFERENCES_OBJECTS
    FOREIGN KEY (REFERENCE)
    REFERENCES TP_OBJECTS (OBJECT_ID) ON DELETE CASCADE
);

CREATE INDEX PARAMS_OBJECT_TP_IDX ON TP_PARAMS (OBJECT_ID);
CREATE INDEX PARAMS_ATTRIBUTE_TP_IDX ON TP_PARAMS (ATTR_ID);
CREATE INDEX PARAMS_OBJECT_ATTRIBUTE_TP_IDX ON TP_PARAMS (OBJECT_ID, ATTR_ID);
CREATE INDEX PARAMS_LIST_VALUES_TP_IDX ON TP_PARAMS (LIST_VALUE_ID);
CREATE INDEX PARAMS_REFERENCE_TP_IDX ON TP_PARAMS (REFERENCE);

/